### ISSUE TITLE
ftp errors

### ISSUE THREAD

**Issue by gpcimino** [PyFilesystem/pyfilesystem2#21]
Hi all!

I discovered pyfilesystem2 and it is great!
However I am experiencing some problems with FTP file systems.
In particular I am experiencing different behavior depending on the type if FTP server I am talking with.
I will report a case that is easy to reproduce.

Client: pyfilesystem2 (last committed version from github) on python 3.5.1 32bin Windows 7 
Server: pyftpdlib  (last committed version from github) on python 3.5.1 32bin Windows 7

```
from fs.copy import copy_fs

addr = '127.0.0.1'
usr = 'anonymous'
psw = "123"
ftproot = "/data/"

try:
    ftpurl = 'ftp://' + usr + ":" + psw + "@" + addr + ftproot
    print("copy files between ftp "+ftpurl+" an local filesystems... ", end='')
    
    copy_fs(ftpurl, 'osfs://d:/tmp2/target/')
    print("OK")
except Exception as ex:
    print("FAILS")  
```

Run ftp server as:

```
mkdir d:\\ftproot\\data
#copy in d:\\ftproot\\data 3 files: 
# one 50Kb jpg image
# 3 byte txt file
# 40MB txt file

python -m pyftpdlib  -p 21 -d d:\\ftproot
```

The transfer of the 40Mb txt file fails.
Could anybody suggest why?

Note that i have similar problems with a production proftpd server (very old version).

Thanks
Giampaolo

**Comment by willmcgugan** [comment]
I can reproduce the error. Thanks.

**Comment by gpcimino** [comment]
Ok thanks! Looking forward to have this fixed!

**Comment by willmcgugan** [comment]
I've pushed some fixes to the ftpfs. Still a work in progress. You might want to try the latest in master or `pip install fs==2.0.1a0`.

**Comment by gpcimino** [comment]
@willmcgugan, 

Thanks, the fix works. The error reported in the first post is now fixed.

However ;-) I will open another (similar) issue for a problem with proftp server.

Thanks
GP

**Comment by willmcgugan** [comment]
Great. I still have some tests failing. I'll leave this issue open until there is an official release.

**Comment by willmcgugan** [comment]
https://github.com/PyFilesystem/pyfilesystem2/releases/tag/v2.0.2
